sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "DIfa7vVeoosmgzw9f8WChNzjZs8ZLLw44z/TQMAH6Ap60zhRFjiEM9wSRDnyTRJvQXf5VK9Wj/LR4tO2Uy0tcdpk9NxaSepYFZKLCkjyIBtrjWb5Facmr0N9Ar88RBhLEJq90kRwIj+1sC9LaMCuGq7R7pJVXMlyweiimWBCEdupTXOM86gG84/gZNSs5m64gw0mJjGA/F+OBkj5fbca5H1+6X+dm337Q4yOFbPXoCrZPGmRkChqg+WTw8id4khE5+c5fV79G0nLb1cAStUk8hiKwpS26KDrjZT8coieiFhZPOp8OgfAMyC5tlKarWNkJnplr9C4skuIJhmFEyUBO15pLqHMme9C4D1TfjnuCrD1RVpCIiIXsjlxKZmEevHxUDu8pT4OQv4V3GyXqf5C+DQiIziXGgp+EFmpEtWxFhvqRHhYRF8D5yLrVtygmLAjp1erx+9ivcY8qtQ3qJDUd3GoEGFah8IC2/kObTLBTEecf9GViWzsthw24ZFpkSt834N51TjApJaSU02Gex+Cru6AIrsNX71RK9i6//Y7tgkquxBNfXnDDEP5CDrnKkvF21R/yC64S7hbzKf4oaleMwS5bfJRvprjZ+tfsGfAoCyeKQsX5PBPvjHKZQsyAOCIYrU08dZJ9T7pHLMF1FPKcCb6MYd/3sU5dQP5+4xdISw="
  - secure: "k7sQnB2lyAi3yO3HSw8sj1E0lR59E6RW+GngDSVn9wtVBNaiq/nbgqsw3UU8P3UqrQrKOrCCuWJPaCKxo5gNL4NR8wNDD6mu9B5luLj6pNwsm85kZJzP7SNcvmWJfDq+u/QmXtH47XlXHOuHwwDBXDFKiu5YS6scMYtLWBHbOlmQCyKJjGlHTwJlGGGZzqFIau+86AcDzLeDbjZzpSOhc1yzWhaGXZ9f7lKVNDBXaahW0TRYHDrU5JnLZjI7haThH9x+ORoO/tviJeI1KfIEtyNNE1nV1FhAhEUQyeMWNBI4nqSAI3xcpDjowyMSgqeaChMDLzFDGvG9vF6Ba+v6s92usXk/It5hI5VlX3wx64RQ1DrLMJUfoh/xK0Cdkv+HoPMW7CsZv9Pl2NtDNKYIpF53l3GyQrYWdvdXHyGxsoOlA3ZULVwwBIqygmTwD8bAXC+6taw4zR4JbhW/EUUNP0WSenHzAHFvi3v0RQ2FvFFXzqHVlaoxIXu35rHeWcXfdgZGkPX+fhjJfSdBBdUVrCywnZsurD2s4C7f9Op3pM3z88FSrUzGj3jZI3o9hKOf8p3M+mmP1PNEOJYmExWJms3J0lCQ7or7A2Q9yGdGLixDAdpYKeHkIl08hVMmojtEfTum0mAfz0xLvVEN/yoOINOB/Wfc7y703dZR+hlczcE="
  - secure: "Qf73NU+HSimHlWjq0qVwxpyE6HvZxTdH0+JQrRUHBj5hl4HG9oxPmuGyTe8zN7P+cv5Lc8tIvdKq0tjir7Od7+P1zSwSR84QNtuk8NkcpP5FgCVeV65wnmp7vg7CHZnrlchhndpLI4XH/E39U8BB8QEqxZsNFpnNhoZ/GnSHiYIbFVLS7cWz9AilokPCfyeX8YiAA7x+QGO3ZqxZHmCapLIbu+LgBuy09wEBShhZalGsl/wzIdQfCa83dkQ+onq97mOPRNWqPJJnC581+qHuTs6XoJCvyqfmpiUaJ2KzHpsix03976CuFzIVHN/Y1jAKoQ7EatlwMATIfrg9ynAOlJ6PtZiyoe/5NSTEvByKM65N9+lH/FjD+QwPks3svkNU+igfbVuXQmG1+bsoMtf4zl6Riu436Z7U8d8P/hYxMrNzZGECFhLP8Wvx+kjb5WeBYSC8uy+dzzuPjx9iC2ejM7WtBdlMWfncQZ4AkROmVFgkYnI1dSEDuC0rfA/hVfqAkPmcKaoNfonNiyZesRa9HPU11rAaTl6wzwJlHfzvwBVV4ROxhVa7jt3ow/QceLcSo1ndPdbGoNCSp0bIEPC+dc/jfC+OSz8QiS2p9V43iwOgpnyb8uwM9RR5nY0kMPckosdOe4S6bAMP6dDBsYadOQd1Ot4aotBcqalaGgPbSac="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
